version: 1.0.{build}

image: 
  - Ubuntu
  - Visual Studio 2022
configuration: Release

for:
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sudo apt-get update
    - sudo apt-get install g++-aarch64-linux-gnu
  build_script:
    - mkdir build
    - cd build
    - cmake ../prj/cmake -DSIMD_TOOLCHAIN="/your_toolchain/usr/bin/aarch64-linux-gnu-g++" -DSIMD_TARGET="aarch64" -DCMAKE_BUILD_TYPE="Release"
    - make
-
  matrix:
    only:
      - image: Visual Studio 2022

  build:
    project: prj\vs2022\Simd.sln
