version: 1.0.{build}

configuration:
  - Release
  - Debug
  
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: ppc64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: arm
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: aarch64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: ARM64
      
for:
-
  matrix:
    only:
      - image: Ubuntu
      - platform: ppc64
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-powerpc-linux-gnu
  build_script:
    - mkdir build
    - cd build
    - cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/powerpc-linux-gnu-g++" -DSIMD_TARGET="ppc64" -DCMAKE_BUILD_TYPE="$CONFIGURATION"
    - make
-
  matrix:
    only:
      - image: Ubuntu
      - platform: arm
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-arm-linux-gnueabihf
  build_script:
    - mkdir build
    - cd build
    - sh: cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/arm-linux-gnueabihf-g++" -DSIMD_TARGET="arm" -DCMAKE_BUILD_TYPE="$CONFIGURATION"
    - make  
-
  matrix:
    only:
      - image: Ubuntu
      - platform: aarch64
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-aarch64-linux-gnu
  build_script:
    - mkdir build
    - cd build
    - sh: cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/aarch64-linux-gnu-g++" -DSIMD_TARGET="aarch64" -DCMAKE_BUILD_TYPE="$CONFIGURATION"
    - make

-
  matrix:
    only:
      - image: Visual Studio 2022
  build:
    project: prj\vs2022\Simd.sln
    verbosity: minimal
    parallel: true
-
  matrix:
    only:
      - image: Visual Studio 2022
      - platform: ARM64
  build_script:
    - mkdir build
    - cd build
    - cmake ..\prj\cmake -G "Visual Studio 17 2022" -T v143 -A ARM64 -DSIMD_TOOLCHAIN="" -DSIMD_TARGET="" -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
    - cmake --build . -j --config Release --target install
