version: 1.0.{build}

image: 
  - Ubuntu
  - Visual Studio 2022
configuration: Release

for:
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-powerpc-linux-gnu
  build_script:
    - mkdir build
    - cd build
    - cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/powerpc-linux-gnu-g++" -DSIMD_TARGET="ppc64" -DCMAKE_BUILD_TYPE="Release"
    - make
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-arm-linux-gnueabihf
  build_script:
    - mkdir build
    - cd build
    - cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/arm-linux-gnueabihf-g++" -DSIMD_TARGET="arm" -DCMAKE_BUILD_TYPE="Release"
    - make
    
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-aarch64-linux-gnu
  build_script:
    - mkdir build
    - cd build
    - cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/aarch64-linux-gnu-g++" -DSIMD_TARGET="aarch64" -DCMAKE_BUILD_TYPE="Release"
    - make

-
  matrix:
    only:
      - image: Visual Studio 2022

  build:
    project: prj\vs2022\Simd.sln
    verbosity: minimal
    parallel: true
