version: 1.0.{build}

configuration:
  - Release
  - Debug
  
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: ppc64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: arm
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: aarch64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: Win32
      
for:
-
  matrix:
    only:
      - image: Ubuntu
      - platform: ppc64
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-powerpc-linux-gnu
  build_script:
    - ECHO Installing %PLATFORM% %CONFIGURATION%
    - mkdir build
    - cd build
    - if [%CONFIGURATION%]==[Release] cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/powerpc-linux-gnu-g++" -DSIMD_TARGET="ppc64" -DCMAKE_BUILD_TYPE="Release"
    - if [%CONFIGURATION%]==[Debug] cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/powerpc-linux-gnu-g++" -DSIMD_TARGET="ppc64" -DCMAKE_BUILD_TYPE="Debug"
    - make
-
  matrix:
    only:
      - image: Ubuntu
      - platform: arm
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-arm-linux-gnueabihf
  build_script:
    - mkdir build
    - cd build
    - sh: cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/arm-linux-gnueabihf-g++" -DSIMD_TARGET="arm" -DCMAKE_BUILD_TYPE=%configuration%
    - make
    
-
  matrix:
    only:
      - image: Ubuntu
      - platform: aarch64
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-aarch64-linux-gnu
  build_script:
    - mkdir build
    - cd build
    - sh: cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/aarch64-linux-gnu-g++" -DSIMD_TARGET="aarch64" -DCMAKE_BUILD_TYPE=%configuration%
    - make

-
  matrix:
    only:
      - image: Visual Studio 2022
      - platform: Win32
  build:
    project: prj\vs2022\Simd.sln
    verbosity: minimal
    parallel: true
