version: 1.0.{build}
  
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: ppc64
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: ppc64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: arm
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: arm
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: aarch64
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      platform: aarch64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: x64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: x64
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: Win32
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: Win32
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      platform: x64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      platform: x64
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      platform: Win32
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      platform: Win32
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: Win32
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: Win32
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: x64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: x64
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: Win32
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: Win32
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: ARM64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: ARM64
      configuration: Debug

for:
-
  matrix:
    only:
      - image: Ubuntu
      - platform: ppc64
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-powerpc-linux-gnu
  build_script:
    - mkdir build
    - cd build
    - cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/powerpc-linux-gnu-g++" -DSIMD_TARGET="ppc64" -DCMAKE_BUILD_TYPE="$CONFIGURATION"
    - make
  artifacts:
    - path: build/libSimd.a
      name: library
  test_script:
    - sh: ls -l
    - sh: ./Test -m=a -tt=1 -f=Sobel -ot=log.txt
-
  matrix:
    only:
      - image: Ubuntu
      - platform: arm
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-arm-linux-gnueabihf
  build_script:
    - mkdir build
    - cd build
    - sh: cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/arm-linux-gnueabihf-g++" -DSIMD_TARGET="arm" -DCMAKE_BUILD_TYPE="$CONFIGURATION"
    - make
  artifacts:
    - path: build/libSimd.a
      name: library
  test_script:
    - sh: build/Test -m=a -tt=1 -f=Sobel -ot=log.txt
-
  matrix:
    only:
      - image: Ubuntu
      - platform: aarch64
  install:
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install g++-aarch64-linux-gnu
  build_script:
    - mkdir build
    - cd build
    - sh: cmake ../prj/cmake -DSIMD_TOOLCHAIN="/usr/bin/aarch64-linux-gnu-g++" -DSIMD_TARGET="aarch64" -DCMAKE_BUILD_TYPE="$CONFIGURATION"
    - make
  artifacts:
    - path: build/libSimd.a
      name: library
  test_script:
    - sh: build/Test -m=a -tt=1 -f=Sobel -ot=log.txt
-
  matrix:
    only:
      - image: Visual Studio 2022
      - platform: x64
  build:
    project: prj\vs2022\Simd.sln
    verbosity: minimal
    parallel: true
  artifacts:
    - path: bin\v143\%platform%\%configuration%\Simd.dll
      name: library
  test_script:
    - cmd: prj\cmd\TestVisualStudio.cmd
-
  matrix:
    only:
      - image: Visual Studio 2022
      - platform: Win32
  build:
    project: prj\vs2022\Simd.sln
    verbosity: minimal
    parallel: true
  artifacts:
    - path: bin\v143\%platform%\%configuration%\Simd.dll
      name: library
  test_script:
    - cmd: prj\cmd\TestVisualStudio.cmd
-
  matrix:
    only:
      - image: Visual Studio 2019
      - platform: x64
  build:
    project: prj\vs2019\Simd.sln
    verbosity: minimal
    parallel: true
  artifacts:
    - path: bin\v142\%platform%\%configuration%\Simd.dll
      name: library
  test_script:
    - cmd: prj\cmd\TestVisualStudio.cmd
-
  matrix:
    only:
      - image: Visual Studio 2019
      - platform: Win32
  build:
    project: prj\vs2019\Simd.sln
    verbosity: minimal
    parallel: true
  artifacts:
    - path: bin\v142\%platform%\%configuration%\Simd.dll
      name: library
  test_script:
    - cmd: prj\cmd\TestVisualStudio.cmd
-
  matrix:
    only:
      - image: Visual Studio 2017
      - platform: x64
  build:
    project: prj\vs2017\Simd.sln
    verbosity: minimal
    parallel: true
  artifacts:
    - path: bin\v141\%platform%\%configuration%\Simd.dll
      name: library
  test_script:
    - cmd: prj\cmd\TestVisualStudio.cmd
-
  matrix:
    only:
      - image: Visual Studio 2017
      - platform: Win32
  build:
    project: prj\vs2017\Simd.sln
    verbosity: minimal
    parallel: true
  artifacts:
    - path: bin\v141\%platform%\%configuration%\Simd.dll
      name: library
  test_script:
    - cmd: prj\cmd\TestVisualStudio.cmd
-
  matrix:
    only:
      - image: Visual Studio 2015
      - platform: x64
  build:
    project: prj\vs2015\Simd.sln
    verbosity: minimal
    parallel: true
  artifacts:
    - path: bin\v140\%platform%\%configuration%\Simd.dll
      name: library
  test_script:
    - cmd: prj\cmd\TestVisualStudio.cmd
-
  matrix:
    only:
      - image: Visual Studio 2015
      - platform: Win32
  build:
    project: prj\vs2015\Simd.sln
    verbosity: minimal
    parallel: true
  artifacts:
    - path: bin\v140\%platform%\%configuration%\Simd.dll
      name: library
  test_script:
    - cmd: prj\cmd\TestVisualStudio.cmd
-
  matrix:
    only:
      - image: Visual Studio 2022
      - platform: ARM64
  build_script:
    - mkdir build
    - cd build
    - cmake ..\prj\cmake -G "Visual Studio 17 2022" -T v143 -A ARM64 -DSIMD_TOOLCHAIN="" -DSIMD_TARGET="" -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
    - cmake --build . -j --config Release --target install
