version: 1.0.{build}

image: 
  - Ubuntu
  - Visual Studio 2022
configuration: Release

for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%/prj/cmake"
    - cmake .
-
  matrix:
    only:
      - image: Visual Studio 2022

  build:
    project: prj\vs2022\Simd.sln
